export const AGENT_PROJECTS = Object.freeze([
  {
    id: "content-matrix",
    index: "01",
    title: "内容矩阵 Agent",
    shortTitle: "内容矩阵",
    responsibility: "负责账号定位、栏目结构、平台分工和更新节奏。",
    input: "业务目标、产品、平台与目标人群",
    output: "内容矩阵方案",
    icon: "▦",
    accent: "violet",
    complianceRequired: true,
  },
  {
    id: "competitor-insight",
    index: "02",
    title: "竞品洞察 Agent",
    shortTitle: "竞品洞察",
    responsibility: "负责竞品采集、内容拆解、差异判断和机会识别。",
    input: "竞品链接、截图、数据与分析要求",
    output: "竞品洞察报告",
    icon: "⌕",
    accent: "blue",
    complianceRequired: false,
  },
  {
    id: "topic-planning",
    index: "03",
    title: "选题策划 Agent",
    shortTitle: "选题策划",
    responsibility: "负责人群场景、需求问题、选题池和排期建议。",
    input: "内容矩阵、竞品洞察与产品资料",
    output: "选题清单",
    icon: "✦",
    accent: "orange",
    complianceRequired: true,
  },
  {
    id: "title-planning",
    index: "04",
    title: "标题策划 Agent",
    shortTitle: "标题策划",
    responsibility: "负责标题方向、搜索词、点击表达和风险检查。",
    input: "选题、平台与目标人群",
    output: "标题方案",
    icon: "Aa",
    accent: "pink",
    complianceRequired: true,
  },
  {
    id: "media-article",
    index: "05",
    title: "新媒体图文 Agent",
    shortTitle: "新媒体图文",
    responsibility: "负责正文、内容结构、配图规划和多平台改写。",
    input: "选题、标题与品牌资料",
    output: "图文内容包",
    icon: "◫",
    accent: "cyan",
    complianceRequired: true,
  },
  {
    id: "super-writing",
    index: "06",
    title: "超级 AI 写作 Agent",
    shortTitle: "超级写作",
    responsibility: "负责长文、私域、品牌稿和知识库驱动写作。",
    input: "写作任务、品牌资料与历史稿件",
    output: "完整稿件",
    icon: "✎",
    accent: "indigo",
    complianceRequired: true,
  },
  {
    id: "viral-speech",
    index: "07",
    title: "爆款口播 Agent",
    shortTitle: "爆款口播",
    responsibility: "负责爆款结构拆解、传播钩子和自然口播生成。",
    input: "对标内容、主题与产品资料",
    output: "口播脚本包",
    icon: "▶",
    accent: "red",
    complianceRequired: true,
  },
  {
    id: "lead-video",
    index: "08",
    title: "获客视频 Agent",
    shortTitle: "获客视频",
    responsibility: "负责分镜、配音、画面、字幕和成片生产流程。",
    input: "口播脚本、素材与品牌规范",
    output: "视频生产包",
    icon: "◉",
    accent: "green",
    complianceRequired: true,
  },
  {
    id: "data-review",
    index: "09",
    title: "数据复盘 Agent",
    shortTitle: "数据复盘",
    responsibility: "负责流量、转化、内容产能、复购和行动诊断。",
    input: "平台数据、投放数据与内容结果",
    output: "复盘报告与行动清单",
    icon: "↗",
    accent: "yellow",
    complianceRequired: false,
  },
]);

export const AGENT_IDS = Object.freeze(
  AGENT_PROJECTS.map((agent) => agent.id),
);

export function getAgentById(agentId) {
  return AGENT_PROJECTS.find((agent) => agent.id === agentId) ?? null;
}
